name: Scheduled Action Every 20 Minutes

on:
  schedule:
    # Runs every 20 minutes
    - cron: '* * * * *'

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This action is running every 20 minutes!"
          mvn test  -Dcucumber.options="--tags @C12600" -Dhost="https://www.google.com/" -Dbrowser=CHROMER

