name: Scheduled Action

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run:  mvn test  -Dcucumber.options="--tags @C12600" -Dhost="https://www.google.com/" -Dbrowser=CHROMER
